### ISSUE TITLE
rss

### ISSUE THREAD

**Issue by chovy** [laktak/any-json#1]
Can this be used as a library?
Does it work with RSS?

**Comment by laktak** [comment]
> Can this be used as a library?

I haven't had time to write a doc so you'd need to take a look at https://github.com/laktak/any-json/blob/master/lib/index.js

e.g.
```
var any=require("any-json");
any.async.convert(text, "xml", {}, function(err, obj) {
});
```

> Does it work with RSS?

RSS is XML so specify `xml` as format.
