### ISSUE TITLE
Parsing an array returns only last element

### ISSUE THREAD

**Issue by Nic2012** [laktak/any-json#2]
If I have the following string:
```
Label: ISO Speed
Type: RADIO
Current: 200
Choice: 0 200
Choice: 1 250
Choice: 2 320
Choice: 3 400
Choice: 4 500
Choice: 5 640
Choice: 6 800
Choice: 7 1000
Choice: 8 1250
Choice: 9 1600
```
any-json -format=yaml will return
```
{
  "Label": "ISO Speed",
  "Type": "RADIO",
  "Current": 200,
  "Choice": "9 1600"
}
```
So only last element will return, but is there any other option to set to return it complete ?
Best regards,
Nic

**Comment by laktak** [comment]
I'm no YAML expert but to define an array you'll need to use `-` like:

```
Label: ISO Speed
Type: RADIO
Current: 200
Choice: 
  - 200
  - 250
  - 320
  - 400
  - 500
  - 640
  - 800
  - 1000
  - 1250
  - 1600
```

That should give you the correct output.

**Comment by Nic2012** [comment]
No, it makes no differences if an array element has the content "Choice: 0 200" or "200". The problem that input string is formatted from the beginning like this
```
Label: ISO Speed
Type: RADIO
Current: 200
Choice: 0 200
Choice: 1 250
Choice: 2 320
Choice: 3 400
Choice: 4 500
Choice: 5 640
Choice: 6 800
Choice: 7 1000
Choice: 8 1250
Choice: 9 1600
```

**Comment by laktak** [comment]
Like I said, you are not defining an array. Take a look at the YAML syntax.

You can try an online yaml parser and you'll get the same result. e.g. at http://yaml-online-parser.appspot.com/

**Comment by Nic2012** [comment]
Aha, i understand now, thank you.
